import marimo

__generated_with = "0.20.4"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Loading from `.` and `public` using `mo.image`
    """)
    return


@app.cell
def _(mo):
    mo.image(src="marimo-logo.svg")
    return


@app.cell
def _(mo):
    mo.image(src="public/marimo-logo.svg")
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Use Markdown `![logo](marimo-logo.svg)`

    [logo](marimo-logo.svg)

    Shows alt text as link but not image.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Use Markdown `![logo](/marimo-logo.svg)`

    ![logo](/marimo-logo.svg)

    Shows alt text as plain text but not image.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Use Markdown `![logo](/public/marimo-logo.svg)`

    ![logo](/public/marimo-logo.svg)

    Shows image.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Now try an image generated by draw.io

    ![concept map](/public/01_concepts.svg)
    """)
    return


if __name__ == "__main__":
    app.run()
